const mongoose=require('mongoose');

const productSchema=mongoose.Schema({
    gender:{
        type:String,
        required:true
    },
    category:{
        type:String,
        required:true
    },
    style:{
        type:String,
        required:true
    },
    styleimg:{
        publicId:String,
        url:String
    },
    name:{
        type:String,
        required:true
    },
    description:{
        type:String,
        required:true
    },
    color:{
        type:String,
        required:true
    },
    brand:{
        type:String,
        required:true
    },
    mrp:{
        type:Number,
        required:true
    },
    price:{
        type:Number,
        required:true
    },
    image:{
        publicId:String,
        url:String
    },
    rating:{
        type:Number,
        required:true
    },
    ratingcount:{
        type:Number,
        required:true
    }
})

module.exports=mongoose.model('product',productSchema);